spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1433953151
      url: jdbc:mysql://127.0.0.1:3306/cloud2210?useUnicode=true&characterEncoding=utf8&useSSL=false
      max-active: 40
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
  sleuth:
    sampler:
      rate: 10
  application:
    name: cloud-orders #服务器名称 必须有 需要到nacos注册
  cloud:
    # nacos的配置
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
    
    sentinel:
      eager: true
      transport:
        port: 8719
        dashboard: localhost:8888
      web-context-unify: false
    datasource:
      flow:
        nacos:
          server-addr: ${spring.cloud.nacos.server-addr}
          username: ${spring.cloud.nacos.username}
          password: ${spring.cloud.nacos.password}
          groupId: SENTINEL_GROUP
          dataId: ${spring.application.name}-flow-rules
          rule-type: flow
      degrade:
        nacos:
          server-addr: ${spring.cloud.nacos.server-addr}
          username: ${spring.cloud.nacos.username}
          password: ${spring.cloud.nacos.password}
          groupId: SENTINEL_GROUP
          dataId: ${spring.application.name}-degrade-rules
          rule-type: degrade
      param-flow:
        nacos:
          server-addr: ${spring.cloud.nacos.server-addr}
          username: ${spring.cloud.nacos.username}
          password: ${spring.cloud.nacos.password}
          groupId: SENTINEL_GROUP
          dataId: ${spring.application.name}-param-rules
          rule-type: param-flow
      system:
        nacos:
          server-addr: ${spring.cloud.nacos.server-addr}
          username: ${spring.cloud.nacos.username}
          password: ${spring.cloud.nacos.password}
          groupId: SENTINEL_GROUP
          dataId: ${spring.application.name}-system-rules
          rule-type: system
      authority:
        nacos:
          server-addr: ${spring.cloud.nacos.server-addr}
          username: ${spring.cloud.nacos.username}
          password: ${spring.cloud.nacos.password}
          groupId: SENTINEL_GROUP
          dataId: ${spring.application.name}-authority-rules
          rule-type: authority

# 端口号
server:
  port: ${port:8081}



ribbon:
  eager-load:
    enabled: true
    clients:
      - cloud-jifen

#
feign:
  sentinel:
    enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    org.itck.orders.mapper: debug


seata:
  enabled: true
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos

